version: '3.8'

services:
  app:
    container_name: express-auth
    restart: unless-stopped
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: pass_postgres
      POSTGRES_DB: express_auth_test
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
